//import type { NextPage } from "next";
import { Console } from "console";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Banner, Header } from "../components";
import { sanityClient, urlFor } from "../sanity";
import { Post } from "../sanity-projectfiles/typings";

interface Props {
    posts: [Post];
}

const Home /* : NextPage */ = ({ posts }: Props) => {
    return (
        <div className="max-w-7xl mx-auto">
            <Head>
                <title>Medium Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <Banner />

            {/* POSTS */}
            <div>
                {posts.map((post) => (
                    <Link key={post._id} href={`/post/${post.slug.current}`}>
                        <div>
                            <h1>this is a test</h1>
                        </div>
                    </Link>
                ))}
            </div>
        </div>
    );
};

export default Home;

export const getServerSideProps = async () => {
    const query = `*[_type == "post"]{
        _id,
        title,
        author -> {
        name,
        image
      }, 
      description,
      mainImage,
      slug
      }`;

    const posts = await sanityClient.fetch(query);

    return {
        props: { posts },
    };
};
